export const GET_ALL_BUILDINGS =  'GET_ALL_BUILDINGS'; 
export const SELECTED_BUILDING = 'SELECTED_BUILDING';
export const GET_ALL_BUILDINGS_ERROR = 'GET_ALL_BUILDINGS_ERROR';

export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR'